#in command terminal use command "docker-compose up --build" to create new docker image
#can run individual service clusters through "docker-compose up zookeeper -d"

version: "3"
services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  #can create entirely new docker-compose.yml file with just the generator app
  #run docker-compose from generator folder directory to obtain random transactions
  generator:
    build: ./transaction_generator
  
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000
  detector:
    build: ./fraud_detector

    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud



